# Generated by Django 5.0.6 on 2024-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
