# Generated by Django 5.0.6 on 2024-06-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='datetime',
        ),
    ]
